In [7]:
import pandas as pd
import numpy as np

In [8]:
%matplotlib inline

In [9]:
import matplotlib.pyplot as plt
import seaborn as sns

In [10]:
df = pd.read_excel('Daten/Gewerbe/Leerflaechen-Gewerbe_alle.xlsx', header=9).fillna(0).astype(int)

#df = pd.read_excel('Leerflaechen einzeln.xlsx', index_col=0, header=0)

FileNotFoundError: [Errno 2] No such file or directory: 'Daten/Gewerbe/Leerflaechen-Gewerbe_alle.xlsx'

In [ ]:
df.fillna(0).head()

In [ ]:
list1 = list(df)

In [5]:
list1

NameError: name 'list1' is not defined

In [6]:
#df.info

In [11]:
df_leerflaeche = df[['Leerfläche (m²).1', 'Unnamed: 6', 'Unnamed: 11', 'Unnamed: 3', 'Unnamed: 4']]

In [12]:
df_leerflaeche

,Leerfläche (m²).1,Unnamed: 6,Unnamed: 11,Unnamed: 3,Unnamed: 4
NaN,2018,2017,2017,2015,2014
Ganze Stadt,139664,174381,2,256450,264548
Kreis 1,23805,29535,3,40945,53774
Rathaus,1399,1940,1,2261,2284
Hochschulen,670,797,1,126,2218
Lindenhof,6963,8158,4,7737,7381
City,14773,18640,4,30821,41891
Kreis 2,19520,17542,2,30347,34236
Wollishofen,1741,2224,1,3790,9101
Leimbach,0,0,0,0,401
Enge,17779,15318,2,26557,24734
Kreis 3,11823,14315,1,38728,34681
Alt-Wiedikon,10489,12785,2,33457,26935
Friesenberg,0,0,0,0,0
Sihlfeld,1334,1530,1,5271,7746
Kreis 4,4276,8691,1,7325,7046
Werd,3087,2536,1,610,3026
Langstrasse,555,3574,1,5553,3769
Hard,634,2581,4,1162,251
Kreis 5,4817,3591,0,44909,33643
Gewerbeschule,0,379,0,2344,4311
Escher Wyss,4817,3212,0,42565,29332
Kreis 6,2635,3961,1,5322,2095
Unterstrass,2384,2860,1,5322,1795
Oberstrass,251,1101,1,0,300
Kreis 7,2302,3875,0,3886,3577
Fluntern,0,557,0,66,66
Hottingen,990,2159,1,3030,1208
Hirslanden,1112,1159,1,674,2187
Witikon,200,0,0,116,116
Kreis 8,5995,11065,2,15127,13214
Seefeld,2353,5585,2,9473,8101
Mühlebach,3352,4914,2,4740,4779
Weinegg,290,566,0,914,334
Kreis 9,29739,29526,2,42610,41216
Albisrieden,5383,6127,3,3382,4823
Altstetten,24356,23399,2,39228,36393
Kreis 10,159,285,0,220,1240
Höngg,0,0,0,220,0
Wipkingen,159,285,0,0,1240
Kreis 11,33757,50811,4,25972,38549
Affoltern,98,546,0,200,1095
Oerlikon,13603,5104,1,3101,3299
Seebach,20056,45161,7,22671,34155
Kreis 12,836,1184,1,1059,1277
Saatlen,758,1018,3,514,408
Schwamendingen-Mitte,78,166,0,545,709
Hirzenbach,0,0,0,0,160

In [16]:
df = pd.read_excel('Daten/Gewerbe/Leerflaechen-Gewerbe_alle.xlsx', header=9).fillna(0).astype(int)

#df = pd.read_excel('Leerflaechen einzeln.xlsx', index_col=0, header=0)

In [17]:
df.fillna(0).head()

,Leerfläche (m²),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Leerfläche (m²).1,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Leerflächenziffer,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Leerfläche (m²).2,Unnamed: 16,Unnamed: 17,Unnamed: 18
NaN,2018,2017,2016,2015,2014,2018,2017,2016,2015,2014,2018,2017,2016,2015,2014,2018,2018,2018,2018
Ganze Stadt,187714,243660,237054,256450,264548,139664,174381,193027,207901,214900,1,2,2,2,2,31663,5381,5122,5884
Kreis 1,30550,34710,32201,40945,53774,23805,29535,29807,36180,49692,3,3,3,4,6,2436,1889,214,2206
Rathaus,3504,1940,2261,2261,2284,1399,1940,1315,2113,1856,1,1,1,2,1,128,383,64,1530
Hochschulen,670,1187,340,126,2218,670,797,340,126,2218,0,1,0,0,2,0,0,0,0

In [18]:
list2 = list(df)

In [19]:
list2

['Leerfläche (m²)',
 'Unnamed: 1',
 'Unnamed: 2',
 'Unnamed: 3',
 'Unnamed: 4',
 'Leerfläche (m²).1',
 'Unnamed: 6',
 'Unnamed: 7',
 'Unnamed: 8',
 'Unnamed: 9',
 'Leerflächenziffer',
 'Unnamed: 11',
 'Unnamed: 12',
 'Unnamed: 13',
 'Unnamed: 14',
 'Leerfläche (m²).2',
 'Unnamed: 16',
 'Unnamed: 17',
 'Unnamed: 18']

In [20]:
df_leerflaeche = df[['Leerfläche (m²)', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4']]

In [37]:
df_leerflaeche.head()

             Leerfläche (m²)  Unnamed: 1  Unnamed: 2  Unnamed: 3  Unnamed: 4
NaN                     2018        2017        2016        2015        2014
Ganze Stadt           187714      243660      237054      256450      264548
Kreis 1                30550       34710       32201       40945       53774
Rathaus                 3504        1940        2261        2261        2284
Hochschulen              670        1187         340         126        2218

In [38]:
df.rename(columns=df.iloc[0]).drop(df.index[0])

TypeError: 'Series' objects are mutable, thus they cannot be hashed

TypeError: 'Series' objects are mutable, thus they cannot be hashed

In [39]:
df_leerflaeche[:4]

             Leerfläche (m²)  Unnamed: 1  Unnamed: 2  Unnamed: 3  Unnamed: 4
NaN                     2018        2017        2016        2015        2014
Ganze Stadt           187714      243660      237054      256450      264548
Kreis 1                30550       34710       32201       40945       53774
Rathaus                 3504        1940        2261        2261        2284

In [29]:
#df_leerflaeche.rename(columns = header)

In [30]:
df_leerflaeche.head()

             Leerfläche (m²)  Unnamed: 1  Unnamed: 2  Unnamed: 3  Unnamed: 4
NaN                     2018        2017        2016        2015        2014
Ganze Stadt           187714      243660      237054      256450      264548
Kreis 1                30550       34710       32201       40945       53774
Rathaus                 3504        1940        2261        2261        2284
Hochschulen              670        1187         340         126        2218

In [31]:
new_header = df.iloc[0] #grab the first row for the header
df = df[1:] #take the data less the header row
df.columns = new_header #set the header row as the df header

In [32]:
df_auswahl = df[['2018', '2017']]


#df_auswahl = df[['Total Leerfläche (m²)', 'Unnamed: 1 Unnamed: 1']]



# df_ohnere_total = df[['Industrie - Total', 'Dienste - Total', 'Total',
#        'Total ohne ausländisch beherrschte Finanz- und Holdinggesellschaften',
#        #'Pro memoria: Grundstücks- und Wohnungswesen',
#        #'Pro memoria: Total inkl. Grundstücks- und Wohnungswesen'
#         ]]

KeyError: "['2018' '2017'] not in index"

In [33]:
df.columns

Int64Index([187714, 243660, 237054, 256450, 264548, 139664, 174381, 193027,
            207901, 214900,      1,      2,      2,      2,      2,  31663,
              5381,   5122,   5884],
           dtype='int64', name='Ganze Stadt')

In [34]:
df_auswahl[0:].reset_index()

NameError: name 'df_auswahl' is not defined

In [ ]:
df[0:]

In [ ]:
df.transpose()

In [ ]:
import plotly.offline as pyo
import plotly.graph_objs as go
import numpy as np

pyo.init_notebook_mode(connected=True)

np.random.seed(42)
random_x = np.random.randint(1,101,100)
random_y = np.random.randint(1,101,100)

data = [go.Scatter(
    x = random_x,
    y = random_y,
    mode = 'markers',
)]
fig = go.Figure(data=data)
pyo.iplot(fig, filename='hover-chart-basic')

In [29]:
import plotly.offline as pyo
import plotly.graph_objs as go
import numpy as np

pyo.init_notebook_mode(connected=True)

trace1 = go.Bar(
    x=['Rathaus', 'Hochschulen', 'Lindenhof', 'City'],
    y=['2014', '2015', '2016', '2017', '2018'],
    name='BE Zoo'
)

trace2 = go.Bar(
    x=['Rathaus', 'Hochschulen', 'Lindenhof', 'City'],
    y=['2014', '2015', '2016', '2017', '2018'],
    name='ZH Zoo'
)

# trace1 = go.Bar(
#     x=['2014', '2015', '2016', '2017', '2018'],
#     y=['Rathaus', 'Hochschulen', 'Lindenhof', 'City'],
#     name='SF Zoo'
# )
# trace2 = go.Bar(
#     x=['2014', '2015', '2016', '2017', '2018'],
#     y=['Rathaus', 'Hochschulen', 'Lindenhof', 'City'],
#     name='LA Zoo'
# )

data = [trace1, trace2]
layout = go.Layout(
    barmode='group'
)

fig = go.Figure(data=data)
pyo.iplot(fig, filename='hover-chart-basic')


# fig = go.Figure(data=data, layout=layout)
# py.iplot(fig, filename='grouped-bar')